function(lr_library name)
	cmake_parse_arguments(ARG "" "" "SOURCES;DEPS" ${ARGN})
	if(ARG_SOURCES)
		add_library(${name} STATIC ${ARG_SOURCES})
		set(scope PUBLIC)
	else()
		add_library(${name} INTERFACE)
		set(scope INTERFACE)
	endif()
	target_include_directories(${name} ${scope} ${PROJECT_SOURCE_DIR}/src)
	if(ARG_DEPS)
		target_link_libraries(${name} ${scope} ${ARG_DEPS})
	endif()
endfunction()

function(lr_executable name)
	cmake_parse_arguments(ARG "" "" "SOURCES;DEPS" ${ARGN})
	add_executable(${name} ${ARG_SOURCES})
	if(ARG_DEPS)
		target_link_libraries(${name} PRIVATE ${ARG_DEPS})
	endif()
endfunction()
